### ISSUE TITLE
APIError: 'An error occurred with foursquare API'

### ISSUE THREAD

**Issue by kennethkoontz** [usebenchmark/benchmarkplaces#35]

**Comment by kennethkoontz** [comment]
```
Traceback (most recent call last):
  File "/Users/kenneth/Projects/benchmark/api/venv/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/kenneth/Projects/benchmark/api/venv/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/kenneth/Projects/benchmark/api/venv/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/kenneth/Projects/benchmark/api/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/kenneth/Projects/benchmark/api/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/kenneth/Projects/benchmark/api/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/kenneth/Projects/benchmark/api/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/kenneth/Projects/benchmark/api/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/kenneth/Projects/benchmark/api/app/decorators.py", line 25, in decorated_function
    return f(*args, **kwargs)
  File "/Users/kenneth/Projects/benchmark/api/app/views.py", line 196, in search_locations
    results = provider.search_places(name, address)
  File "/Users/kenneth/Projects/benchmark-places/benchmarkplaces/providers.py", line 238, in search_places
    raise APIError('An error occurred with %s API' % self.name)
APIError: 'An error occurred with foursquare API'
```
